name: electric_airline
dependencies:
  - pip=24.0
  - python=3.12.2
  - pip:
      - furo==2024.5.6
      - geopandas==1.0.1
      - ipykernel==6.29.5
      - kaleido==0.2.1
      - manim==0.18.1
      - manimpango==0.5.0
      - matplotlib==3.9.1
      - moviepy==1.0.3
      - nbformat==5.10.4
      - numpy-stl==3.1.1
      - opencv-python==4.10.0.82
      - pandas==2.2.2
      - pango==0.0.1
      - plotly==5.22.0
      - psycopg2-binary==2.9.9  # Instead of `psycopg2` with, e.g., Linux `build-essential` package.
      - pyautogui==0.9.54
      - pydantic==2.9.2
      - pywavefront==1.3.3
      - shapely==2.0.4
      - sphinx==7.3.7
      - sphinx-jsonschema
      - sphinxawesome-theme==5.2.0
      - sqlalchemy==2.0.31
      - vpython==7.6.5
