name: green_airliner
dependencies:
  - pip=24.0
  - python=3.12.2
  - pip:
      - furo==2024.5.6
      - ipykernel==6.29.5
      - json-schema-for-humans==1.0.2
      - kaleido==0.2.1
      - manim==0.18.1
      - manimpango==0.5.0
      - matplotlib==3.9.1
      - moviepy==1.0.3
      - nbformat==5.10.4
      - numpy<2
      - opencv-python==4.10.0.82
      - pandas==2.2.2
      - pango==0.0.1
      - plotly==5.22.0
      - pyautogui==0.9.54
      - pydantic==2.9.2
      - pywavefront==1.3.3
      - sphinx-collapse==0.1.3
      - sphinx==7.3.7
      - vpython==7.6.5
