name: electric_airline
dependencies:
  - python
  - pip
  - pip:
      - geopandas
      - ipykernel
      - kaleido
      - matplotlib
      - moviepy
      - nbformat
      - pandas
      - pango
      - psycopg2-binary  # Instead of `psycopg2` with, e.g., Linux `build-essential` package.
      - plotly
      - shapely
      - sqlalchemy
      - numpy-stl
      - pywavefront
      - vpython
      - sphinx
