airliner_config:
  airplane_spec: Lh2FueledA320
  refueling_rate_kW: 2333333333  # 7e12/50 J LH2/min * (60 min/h) / 3600 J/Wh
  initial_energy_level_pc: 100.0
  viz_model: a320
airliner_flight_path_config:
  origin_airport: JFK
  flyover_airports:
    - PIT
    - DEN
  destination_airport: LAX
  takeoff_speed_kmph: 262.5  # mean(240, 285) from https://en.wikipedia.org/wiki/Takeoff
  takeoff_distance_km: 1
  takeoff_leveling_distance_km: 0.1
  rate_of_climb_mps: 70
  climb_leveling_distance_km: 10
  cruise_altitude_km: 10.5  # mean(9.4, 11.6) from https://en.wikipedia.org/wiki/Cruise_%28aeronautics%29
  turning_radius_km: 50
  descent_leveling_distance_km: 10
  rate_of_descent_mps: 100
  landing_leveling_distance_km: 0.1
  landing_distance_km: 1
  landing_speed_kmph: 200
  speed_change_distance_km: 50
n_uavs_per_flyover_airport:
  PIT:
    to_airport: 1  # gets labeled as "PIT-UAV-0"
    from_airport: 1  # "PIT-UAV-1"
  DEN:
    to_airport: 3  # "DEN-UAV-0", "DEN-UAV-1", "DEN-UAV-2"
    from_airport: 2  # "DEN-UAV-3", "DEN-UAV-4"
uavs_config:
  airplane_spec: At200
  refueling_rate_kW: 2333333333  # assumed same as airliner
  initial_energy_level_pc: 100.0
  initial_refueling_energy_level_pc: 100.0
  viz_model: cessna
uavs_flight_path_config:
  takeoff_speed_kmph: 100  # https://en.wikipedia.org/wiki/Takeoff
  takeoff_distance_km: 1
  takeoff_leveling_distance_km: 0.1
  rate_of_climb_mps: 35
  climb_leveling_distance_km: 0.5
  default_cruise_altitude_km: 11.5
  descent_leveling_distance_km: 0.5
  rate_of_descent_mps: 50
  landing_leveling_distance_km: 0.1
  landing_distance_km: 1
  landing_speed_kmph: 200
  arc_radius_km: 1
  airliner_uav_docking_distance_km: 0.0015
  smallest_undocking_distance_from_airport_km: 50
  inter_uav_clearance_km: 15
  airliner_clearance_speed_kmph: 200
  airliner_clearance_distance_km: 5
  default_airliner_clearance_altitude_km: 5
  inter_uav_vertical_dist_km: 1
ratepoints:
  - elapsed_minutes: 0
    rate: 1
  - elapsed_minutes: d_airliner["Airliner-ascended-point"]
    rate: 1
  - elapsed_minutes: d_airliner["Airliner-ascended-point"] + 5
    rate: 30
  # PIT:
  - elapsed_minutes: d_airliner["PIT-UAV-0-on-airliner-docking-point"] - 5
    rate: 30
  - elapsed_minutes: d_airliner["PIT-UAV-0-on-airliner-docking-point"] - 1.5
    rate: 1
  - elapsed_minutes: d_airliner["PIT-UAV-0-on-airliner-undocking-point"] + 1.5
    rate: 1
  - elapsed_minutes: d_airliner["Airliner-curve-over-PIT-midpoint"]
    rate: 3
  - elapsed_minutes: d_airliner["PIT-UAV-1-on-airliner-docking-point"] - 1.5
    rate: 2
  - elapsed_minutes: d_airliner["PIT-UAV-1-on-airliner-undocking-point"] + 1.5
    rate: 2
  - elapsed_minutes: d_airliner["PIT-UAV-1-on-airliner-undocking-point"] + 10
    rate: 50
  # DEN:
  - elapsed_minutes: d_airliner["DEN-UAV-0-on-airliner-docking-point"] - 10
    rate: 50
  - elapsed_minutes: d_airliner["DEN-UAV-0-on-airliner-docking-point"] - 1.5
    rate: 1
  - elapsed_minutes: d_airliner["DEN-UAV-0-on-airliner-undocking-point"] + 1.5
    rate: 1
  - elapsed_minutes: d_airliner["Airliner-curve-over-DEN-midpoint"]
    rate: 3
  - elapsed_minutes: d_airliner["Airliner-curve-over-DEN-midpoint"] + 40
    rate: 30
  # LAX:
  - elapsed_minutes: d_airliner["Airliner-descent-point"] - 5
    rate: 30
  - elapsed_minutes: d_airliner["Airliner-descent-point"]
    rate: 2
  - elapsed_minutes: d_airliner["Airliner-landed-point"] + 5
    rate: 2
viz_config:
  min_frame_duration_s: 0.04
  scene_w: 1800
  scene_h: 900
  zoompoints_config:
    airliner_zoompoints:
      - elapsed_minutes: 0
        zoom: 5
      - elapsed_minutes: d["Airliner-takeoff-point"]
        zoom: 0.5
      - elapsed_minutes: d["Airliner-ascended-point"]
        zoom: 0.5
      - elapsed_minutes: d["Airliner-ascended-point"] + 0.5
        zoom: 0.04
      # PIT:
      - elapsed_minutes: d["PIT-UAV-0-on-airliner-docking-point"] - 1
        zoom: 0.02
      - elapsed_minutes: d["PIT-UAV-0-on-airliner-docking-point"] - 0.3
        zoom: 0.5
      - elapsed_minutes: d["PIT-UAV-0-on-airliner-undocking-point"] - 0.1
        zoom: 10
      - elapsed_minutes: d["PIT-UAV-0-on-airliner-undocking-point"] + 0.5
        zoom: 0.5
      - elapsed_minutes: d_airliner["Airliner-curve-over-PIT-midpoint"] - 5
        zoom: 0.1
      - elapsed_minutes: d_airliner["Airliner-curve-over-PIT-midpoint"]
        zoom: 0.05
      - elapsed_minutes: d_airliner["Airliner-curve-over-PIT-midpoint"] + 5
        zoom: 0.1
      - elapsed_minutes: d["PIT-UAV-1-on-airliner-docking-point"] - 0.3
        zoom: 0.5
      - elapsed_minutes: d["PIT-UAV-1-on-airliner-undocking-point"] - 0.1
        zoom: 10
      - elapsed_minutes: d["PIT-UAV-1-on-airliner-undocking-point"] + 0.5
        zoom: 0.5
      - elapsed_minutes: d["PIT-UAV-1-on-airliner-undocking-point"] + 2
        zoom: 0.02
      - elapsed_minutes: d["PIT-UAV-1-on-airliner-undocking-point"] + 20
        zoom: 0.005
      # DEN:
      - elapsed_minutes: d["DEN-UAV-0-on-airliner-docking-point"] - 5
        zoom: 0.004
      - elapsed_minutes: d["DEN-UAV-0-on-airliner-docking-point"] - 1
        zoom: 0.02
      - elapsed_minutes: d["DEN-UAV-0-on-airliner-docking-point"] - 0.3
        zoom: 0.5
      - elapsed_minutes: d["DEN-UAV-0-on-airliner-undocking-point"] - 0.1
        zoom: 10
      - elapsed_minutes: d["DEN-UAV-0-on-airliner-undocking-point"] + 0.5
        zoom: 0.5
      - elapsed_minutes: d_airliner["Airliner-curve-over-DEN-midpoint"]
        zoom: 0.05
      - elapsed_minutes: d["DEN-UAV-3-on-airliner-docking-point"]
        zoom: 0.5
      - elapsed_minutes: d["DEN-UAV-4-on-airliner-undocking-point"]
        zoom: 0.1
      - elapsed_minutes: d["DEN-UAV-4-on-airliner-undocking-point"] + 1
        zoom: 0.02
      - elapsed_minutes: d["DEN-UAV-4-on-airliner-undocking-point"] + 25
        zoom: 0.002
      # LAX:
      - elapsed_minutes: d["Airliner-descent-point"] - 50
        zoom: 0.002
      - elapsed_minutes: d["Airliner-descent-point"]
        zoom: 0.04
      - elapsed_minutes: d["Airliner-landing-point"]
        zoom: 0.04
      - elapsed_minutes: d["Airliner-landed-point"] + 1
        zoom: 0.5
      - elapsed_minutes: d["Airliner-landed-point"] + 5
        zoom: 5
    uavs_zoompoints_config:
      to_airport:
        - elapsed_minutes: 0
          zoom: 50
        - elapsed_minutes: d["takeoff"] - 2
          zoom: 50
        - elapsed_minutes: d["takeoff"] - 1
          zoom: 1
        - elapsed_minutes: d["ascended"]
          zoom: 1
        - elapsed_minutes: d["ascended"] + 1
          zoom: 5
        - elapsed_minutes: d["arc-start"]
          zoom: 5
        - elapsed_minutes: d["descent-to-airliner"]
          zoom: 0.5
        - elapsed_minutes: d["on-airliner-docking"]
          zoom: 5
        - elapsed_minutes: d["on-airliner-docking"] + 0.1
          zoom: 50
        - elapsed_minutes: d["on-airliner-undocking"] - 0.1
          zoom: 50
        - elapsed_minutes: d["on-airliner-undocking"]
          zoom: 5
        - elapsed_minutes: d["ascended-from-airliner"]
          zoom: 0.5
        - elapsed_minutes: d["descent"]
          zoom: 0.5
        - elapsed_minutes: d["landed"]
          zoom: 5
        - elapsed_minutes: d["landed"] + 2
          zoom: 50
      from_airport:
        - elapsed_minutes: 0
          zoom: 50
        - elapsed_minutes: d["takeoff"] - 2
          zoom: 50
        - elapsed_minutes: d["takeoff"] - 1
          zoom: 1
        - elapsed_minutes: d["ascended"]
          zoom: 1
        - elapsed_minutes: d["ascended"] + 1
          zoom: 5
        - elapsed_minutes: d["descent-to-airliner"]
          zoom: 0.5
        - elapsed_minutes: d["on-airliner-docking"]
          zoom: 5
        - elapsed_minutes: d["on-airliner-docking"] + 0.1
          zoom: 50
        - elapsed_minutes: d["on-airliner-undocking"] - 0.1
          zoom: 50
        - elapsed_minutes: d["on-airliner-undocking"]
          zoom: 5
        - elapsed_minutes: d["ascended-from-airliner"]
          zoom: 0.5
        - elapsed_minutes: d["arc-end"]
          zoom: 0.25
        - elapsed_minutes: d["landed"]
          zoom: 5
        - elapsed_minutes: d["landed"] + 2
          zoom: 50
  landed_uavs_waiting_time_mins: 30
  map_view_config:
    models_scale_factor: 20000
    zoom: 10
